import type { BillingPlanPublic, BillingPlansResponse } from "@/lib/billing/billingApi";

const U = 999_999;

/**
 * Offline / marketing fallback matching production
 * `postsiva-backend/app/modules/billing/plans.py` catalog.
 */
export const MARKETING_BILLING_PLANS_FALLBACK: BillingPlansResponse = {
  yearly_savings_percent: 17,
  trial: { plan_id: "starter", days: 14, card_required: false },
  plans: [
    {
      plan_id: "free",
      display_name: "Free",
      price_monthly_usd: 0,
      price_yearly_usd: 0,
      yearly_savings_percent: 17,
      tagline: "Inbox, schedule, AI & DM agents",
      limits: {
        max_workspaces: 1,
        max_connected_accounts: 1,
        max_team_members_per_workspace: 1,
        posts_per_month: 5,
        ai_credits_per_month: 500,
        scheduled_posts_per_month: 5,
        shared_posts_quota: true,
        connected_account_mode: "oauth_platform",
        max_ai_watcher_enabled: 1,
        max_drafts_per_workspace: 5,
      },
      features: {
        publish_enabled: true,
        drafts_enabled: true,
        scheduling_enabled: true,
        extension_enabled: true,
        inbox_enabled: true,
        ai_composer_enabled: true,
        personas_enabled: true,
        analytics_enabled: true,
        support_enabled: false,
        whatsapp_agent_enabled: true,
        instagram_dm_enabled: true,
        facebook_dm_enabled: true,
        gpt_app_enabled: false,
        mcp_enabled: true,
        api_keys_enabled: true,
        auto_replier_enabled: true,
        piva_agent_enabled: true,
        lead_detection_enabled: false,
        ai_watcher_enabled: true,
        bulk_scheduling_enabled: false,
      },
    },
    {
      plan_id: "starter",
      display_name: "Starter",
      price_monthly_usd: 10,
      price_yearly_usd: 100,
      yearly_savings_percent: 17,
      tagline: "Drafts, schedule, inbox, extension & AI",
      limits: {
        max_workspaces: 3,
        max_connected_accounts: 12,
        max_team_members_per_workspace: 5,
        posts_per_month: 150,
        ai_credits_per_month: 3000,
        scheduled_posts_per_month: 100,
        shared_posts_quota: false,
        connected_account_mode: "publish_identity",
        max_ai_watcher_enabled: U,
        max_drafts_per_workspace: U,
      },
      features: {
        publish_enabled: true,
        drafts_enabled: true,
        scheduling_enabled: true,
        extension_enabled: true,
        inbox_enabled: true,
        ai_composer_enabled: true,
        personas_enabled: true,
        analytics_enabled: true,
        support_enabled: true,
        whatsapp_agent_enabled: true,
        instagram_dm_enabled: true,
        facebook_dm_enabled: true,
        gpt_app_enabled: false,
        mcp_enabled: true,
        api_keys_enabled: true,
        auto_replier_enabled: true,
        piva_agent_enabled: true,
        lead_detection_enabled: false,
        ai_watcher_enabled: true,
        bulk_scheduling_enabled: false,
      },
    },
    {
      plan_id: "pro",
      display_name: "Pro",
      price_monthly_usd: 29,
      price_yearly_usd: 290,
      yearly_savings_percent: 17,
      tagline: "WhatsApp, DM agents, GPT, MCP & automation",
      limits: {
        max_workspaces: 8,
        max_connected_accounts: U,
        max_team_members_per_workspace: U,
        posts_per_month: U,
        ai_credits_per_month: 10000,
        scheduled_posts_per_month: U,
        shared_posts_quota: false,
        connected_account_mode: "publish_identity",
        max_ai_watcher_enabled: U,
        max_drafts_per_workspace: U,
      },
      features: {
        publish_enabled: true,
        drafts_enabled: true,
        scheduling_enabled: true,
        extension_enabled: true,
        inbox_enabled: true,
        ai_composer_enabled: true,
        personas_enabled: true,
        analytics_enabled: true,
        support_enabled: true,
        whatsapp_agent_enabled: true,
        instagram_dm_enabled: true,
        facebook_dm_enabled: true,
        gpt_app_enabled: true,
        mcp_enabled: true,
        api_keys_enabled: true,
        auto_replier_enabled: true,
        piva_agent_enabled: true,
        lead_detection_enabled: true,
        ai_watcher_enabled: true,
        bulk_scheduling_enabled: true,
      },
    },
  ] satisfies BillingPlanPublic[],
};
